### ISSUE TITLE
Combining Pacbio and nanopore

### ISSUE THREAD

**Issue by ghost** [lbcb-sci/ra#1]
Hello, 
how do we feed the 2 types of reads to Ra, for a single assembly? 

thank you

**Comment by rvaser** [comment]
Hello,
two types as in ONT and PB, or either of those plus Illumina?

Best regards,
Robert

**Comment by ghost** [comment]
Hello,
actually for my organism I have
Pacbio data
ONT data
illumina data

So I was planning PacBio + ONT for assembly, and illumina for Racon polishing.

**Comment by rvaser** [comment]
You can merge the PB and ONT FASTA/Q files, run with -x ont if there are more ONT reads (-x pb otherwise). The command will then be: `ra -x ont <combined tgs> <illumina> > assembly.fasta`.

**Comment by ghost** [comment]
Perfect, thank you!
