### ISSUE TITLE
Question about Racon Rounds

### ISSUE THREAD

**Issue by Tdanis** [lbcb-sci/ra#8]
Hello, I have a naive question about Ra.
How many rounds of Racon does it implement during the whole process of assembly construction ?

Thank you for your time

**Comment by rvaser** [comment]
Hello,
Ra employs two iterations of Racon with long reads, and one iteration with short reads if present.

Sorry for the late reply!
Best regards,
Robert

**Comment by Tdanis** [comment]
Thank you for your reply
