### ISSUE TITLE
Release for bioconda?

### ISSUE THREAD

**Issue by apeltzer** [lbcb-sci/ra#9]
Hi! 

can you add a release version so that we can add this to bioconda-recipes? That would be fab, especially as we can then install it easily using `conda install -c bioconda ...`

**Comment by rvaser** [comment]
Done!:)

Best regards,
Robert

**Comment by cgjosephlee** [comment]
Hi, I cannot find ra in bioconda, is it still available? Or it had a different name?

**Comment by rvaser** [comment]
I am not sure if it was included (there was/still is a RNA assembler called Ra in bioconda). Why don't you use Ra's successor, called Raven, instead?

**Comment by cgjosephlee** [comment]
Ok, thank you for quick reply.
